version: '3'
services:
  spire-server:
    build: ./docker/spire-server
    hostname: spire-server
    tty: true
    privileged: true
  echo:
    build: ./docker/echo
    hostname: echo
    tty: true
    privileged: true
    links:
      - spire-server
  web:
    build: ./docker/web
    hostname: web
    tty: true
    privileged: true
    links:
      - spire-server
      - echo
    ports:
      - 8080:8080
